# Board: Generic ESP32-C3 Board (Generic)
# Definition: definitions/boards/generic-esp32c3/manifest.yaml

esphome:
  name: esp32-c3-v2
  friendly_name: esp32-c3-v2

esp32:
  variant: esp32c3
  framework:
    type: esp-idf
    
logger:

##########################################################################
    
output:
  - platform: gpio
    pin:
      number: 3
      mode: output
    id: greenLED
  - platform: gpio
    pin:
      number: 2
      mode: output
    id: oranjeLED

interval:
  - interval: 1000ms
    then:
      - output.turn_on: oranjeLED
      - output.turn_off: greenLED
      - delay: 250ms
      - output.turn_off: oranjeLED
      - output.turn_on: greenLED